# so APPARENTLY there are people who have EDITORS that CAN'T HANDLE SHIFT JIS
# and W***NDOWS MACHINES that CAN'T COMPILE PROPERLY with shift jis files.
# i18n is somewhat of a misnomer since there's not really any internationalization
# going on, this is more so just to make it both easily editable and compileable

import argparse
import csv

parser = argparse.ArgumentParser()
parser.add_argument(
    "input",
    help="the csv containing the strings",
)
parser.add_argument("output", help="the output i18n.hpp")
args = parser.parse_args()


def to_escaped_sequence(s):
    unescaped = s.encode("raw_unicode_escape").decode("unicode_escape")
    return "".join(f"\\x{b:02X}" for b in unescaped.encode("cp932"))


with open(args.output, "w", encoding="utf-8", newline="") as f:
    f.write("#pragma once\n\n")
    f.write("// Autogenerated by scripts/generate_i18n.py\n\n")
    with open(args.input, "r", encoding="utf-8", newline="") as csvfile:
        lines = (line for line in csvfile if not line.lstrip().startswith("#"))
        reader = csv.DictReader(lines, delimiter="|")
        for row in reader:
            f.write(f'#define {row["name"]} "{to_escaped_sequence(row["text"])}"\n')
